version: '3.8'

services:
  api:
    build: .
    container_name: kling-api-service
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - KLING_AI_API_TOKEN=${KLING_AI_API_TOKEN}
      - BASE_URL=${BASE_URL:-https://api.klingai.com/v1}
    # restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
